// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package apidef // import "github.com/RivenZoo/govanityimport/proto/apidef"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type VanityImportMetaInfo struct {
	ModuleImportPath     string   `protobuf:"bytes,1,opt,name=module_import_path,json=moduleImportPath,proto3" json:"module_import_path,omitempty"`
	Vcs                  string   `protobuf:"bytes,2,opt,name=vcs,proto3" json:"vcs,omitempty"`
	RepoUrl              string   `protobuf:"bytes,3,opt,name=repo_url,json=repoUrl,proto3" json:"repo_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VanityImportMetaInfo) Reset()         { *m = VanityImportMetaInfo{} }
func (m *VanityImportMetaInfo) String() string { return proto.CompactTextString(m) }
func (*VanityImportMetaInfo) ProtoMessage()    {}
func (*VanityImportMetaInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_d123e24d66c704a9, []int{0}
}
func (m *VanityImportMetaInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VanityImportMetaInfo.Unmarshal(m, b)
}
func (m *VanityImportMetaInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VanityImportMetaInfo.Marshal(b, m, deterministic)
}
func (dst *VanityImportMetaInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VanityImportMetaInfo.Merge(dst, src)
}
func (m *VanityImportMetaInfo) XXX_Size() int {
	return xxx_messageInfo_VanityImportMetaInfo.Size(m)
}
func (m *VanityImportMetaInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_VanityImportMetaInfo.DiscardUnknown(m)
}

var xxx_messageInfo_VanityImportMetaInfo proto.InternalMessageInfo

func (m *VanityImportMetaInfo) GetModuleImportPath() string {
	if m != nil {
		return m.ModuleImportPath
	}
	return ""
}

func (m *VanityImportMetaInfo) GetVcs() string {
	if m != nil {
		return m.Vcs
	}
	return ""
}

func (m *VanityImportMetaInfo) GetRepoUrl() string {
	if m != nil {
		return m.RepoUrl
	}
	return ""
}

type SourceMetaInfo struct {
	ModuleImportPath     string   `protobuf:"bytes,1,opt,name=module_import_path,json=moduleImportPath,proto3" json:"module_import_path,omitempty"`
	HomeUrl              string   `protobuf:"bytes,2,opt,name=home_url,json=homeUrl,proto3" json:"home_url,omitempty"`
	DirPattern           string   `protobuf:"bytes,3,opt,name=dir_pattern,json=dirPattern,proto3" json:"dir_pattern,omitempty"`
	FilePattern          string   `protobuf:"bytes,4,opt,name=file_pattern,json=filePattern,proto3" json:"file_pattern,omitempty"`
	DocHost              string   `protobuf:"bytes,5,opt,name=doc_host,json=docHost,proto3" json:"doc_host,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SourceMetaInfo) Reset()         { *m = SourceMetaInfo{} }
func (m *SourceMetaInfo) String() string { return proto.CompactTextString(m) }
func (*SourceMetaInfo) ProtoMessage()    {}
func (*SourceMetaInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_d123e24d66c704a9, []int{1}
}
func (m *SourceMetaInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SourceMetaInfo.Unmarshal(m, b)
}
func (m *SourceMetaInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SourceMetaInfo.Marshal(b, m, deterministic)
}
func (dst *SourceMetaInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SourceMetaInfo.Merge(dst, src)
}
func (m *SourceMetaInfo) XXX_Size() int {
	return xxx_messageInfo_SourceMetaInfo.Size(m)
}
func (m *SourceMetaInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SourceMetaInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SourceMetaInfo proto.InternalMessageInfo

func (m *SourceMetaInfo) GetModuleImportPath() string {
	if m != nil {
		return m.ModuleImportPath
	}
	return ""
}

func (m *SourceMetaInfo) GetHomeUrl() string {
	if m != nil {
		return m.HomeUrl
	}
	return ""
}

func (m *SourceMetaInfo) GetDirPattern() string {
	if m != nil {
		return m.DirPattern
	}
	return ""
}

func (m *SourceMetaInfo) GetFilePattern() string {
	if m != nil {
		return m.FilePattern
	}
	return ""
}

func (m *SourceMetaInfo) GetDocHost() string {
	if m != nil {
		return m.DocHost
	}
	return ""
}

type ModuleMetaInfo struct {
	ImportInfo           *VanityImportMetaInfo `protobuf:"bytes,1,opt,name=import_info,json=importInfo,proto3" json:"import_info,omitempty"`
	SourceInfo           *SourceMetaInfo       `protobuf:"bytes,2,opt,name=source_info,json=sourceInfo,proto3" json:"source_info,omitempty"`
	SubImportDirs        []string              `protobuf:"bytes,3,rep,name=sub_import_dirs,json=subImportDirs,proto3" json:"sub_import_dirs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ModuleMetaInfo) Reset()         { *m = ModuleMetaInfo{} }
func (m *ModuleMetaInfo) String() string { return proto.CompactTextString(m) }
func (*ModuleMetaInfo) ProtoMessage()    {}
func (*ModuleMetaInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_d123e24d66c704a9, []int{2}
}
func (m *ModuleMetaInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModuleMetaInfo.Unmarshal(m, b)
}
func (m *ModuleMetaInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModuleMetaInfo.Marshal(b, m, deterministic)
}
func (dst *ModuleMetaInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModuleMetaInfo.Merge(dst, src)
}
func (m *ModuleMetaInfo) XXX_Size() int {
	return xxx_messageInfo_ModuleMetaInfo.Size(m)
}
func (m *ModuleMetaInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ModuleMetaInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ModuleMetaInfo proto.InternalMessageInfo

func (m *ModuleMetaInfo) GetImportInfo() *VanityImportMetaInfo {
	if m != nil {
		return m.ImportInfo
	}
	return nil
}

func (m *ModuleMetaInfo) GetSourceInfo() *SourceMetaInfo {
	if m != nil {
		return m.SourceInfo
	}
	return nil
}

func (m *ModuleMetaInfo) GetSubImportDirs() []string {
	if m != nil {
		return m.SubImportDirs
	}
	return nil
}

type SubImportDirToRoot struct {
	SubImportDir         string   `protobuf:"bytes,1,opt,name=sub_import_dir,json=subImportDir,proto3" json:"sub_import_dir,omitempty"`
	RootImportDir        string   `protobuf:"bytes,2,opt,name=root_import_dir,json=rootImportDir,proto3" json:"root_import_dir,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubImportDirToRoot) Reset()         { *m = SubImportDirToRoot{} }
func (m *SubImportDirToRoot) String() string { return proto.CompactTextString(m) }
func (*SubImportDirToRoot) ProtoMessage()    {}
func (*SubImportDirToRoot) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_d123e24d66c704a9, []int{3}
}
func (m *SubImportDirToRoot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubImportDirToRoot.Unmarshal(m, b)
}
func (m *SubImportDirToRoot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubImportDirToRoot.Marshal(b, m, deterministic)
}
func (dst *SubImportDirToRoot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubImportDirToRoot.Merge(dst, src)
}
func (m *SubImportDirToRoot) XXX_Size() int {
	return xxx_messageInfo_SubImportDirToRoot.Size(m)
}
func (m *SubImportDirToRoot) XXX_DiscardUnknown() {
	xxx_messageInfo_SubImportDirToRoot.DiscardUnknown(m)
}

var xxx_messageInfo_SubImportDirToRoot proto.InternalMessageInfo

func (m *SubImportDirToRoot) GetSubImportDir() string {
	if m != nil {
		return m.SubImportDir
	}
	return ""
}

func (m *SubImportDirToRoot) GetRootImportDir() string {
	if m != nil {
		return m.RootImportDir
	}
	return ""
}

type ImportMetaInfoReq struct {
	ImportPath           string   `protobuf:"bytes,1,opt,name=import_path,json=importPath,proto3" json:"import_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImportMetaInfoReq) Reset()         { *m = ImportMetaInfoReq{} }
func (m *ImportMetaInfoReq) String() string { return proto.CompactTextString(m) }
func (*ImportMetaInfoReq) ProtoMessage()    {}
func (*ImportMetaInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_d123e24d66c704a9, []int{4}
}
func (m *ImportMetaInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportMetaInfoReq.Unmarshal(m, b)
}
func (m *ImportMetaInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportMetaInfoReq.Marshal(b, m, deterministic)
}
func (dst *ImportMetaInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportMetaInfoReq.Merge(dst, src)
}
func (m *ImportMetaInfoReq) XXX_Size() int {
	return xxx_messageInfo_ImportMetaInfoReq.Size(m)
}
func (m *ImportMetaInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportMetaInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_ImportMetaInfoReq proto.InternalMessageInfo

func (m *ImportMetaInfoReq) GetImportPath() string {
	if m != nil {
		return m.ImportPath
	}
	return ""
}

type ImportMetaInfoResp struct {
	Ret                  int32           `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	Msg                  string          `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	TraceId              string          `protobuf:"bytes,3,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	MetaInfo             *ModuleMetaInfo `protobuf:"bytes,4,opt,name=meta_info,json=metaInfo,proto3" json:"meta_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ImportMetaInfoResp) Reset()         { *m = ImportMetaInfoResp{} }
func (m *ImportMetaInfoResp) String() string { return proto.CompactTextString(m) }
func (*ImportMetaInfoResp) ProtoMessage()    {}
func (*ImportMetaInfoResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_d123e24d66c704a9, []int{5}
}
func (m *ImportMetaInfoResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportMetaInfoResp.Unmarshal(m, b)
}
func (m *ImportMetaInfoResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportMetaInfoResp.Marshal(b, m, deterministic)
}
func (dst *ImportMetaInfoResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportMetaInfoResp.Merge(dst, src)
}
func (m *ImportMetaInfoResp) XXX_Size() int {
	return xxx_messageInfo_ImportMetaInfoResp.Size(m)
}
func (m *ImportMetaInfoResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportMetaInfoResp.DiscardUnknown(m)
}

var xxx_messageInfo_ImportMetaInfoResp proto.InternalMessageInfo

func (m *ImportMetaInfoResp) GetRet() int32 {
	if m != nil {
		return m.Ret
	}
	return 0
}

func (m *ImportMetaInfoResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ImportMetaInfoResp) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

func (m *ImportMetaInfoResp) GetMetaInfo() *ModuleMetaInfo {
	if m != nil {
		return m.MetaInfo
	}
	return nil
}

type UpdateModuleMetaInfoReq struct {
	Action               string          `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	MetaInfo             *ModuleMetaInfo `protobuf:"bytes,2,opt,name=meta_info,json=metaInfo,proto3" json:"meta_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UpdateModuleMetaInfoReq) Reset()         { *m = UpdateModuleMetaInfoReq{} }
func (m *UpdateModuleMetaInfoReq) String() string { return proto.CompactTextString(m) }
func (*UpdateModuleMetaInfoReq) ProtoMessage()    {}
func (*UpdateModuleMetaInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_d123e24d66c704a9, []int{6}
}
func (m *UpdateModuleMetaInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateModuleMetaInfoReq.Unmarshal(m, b)
}
func (m *UpdateModuleMetaInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateModuleMetaInfoReq.Marshal(b, m, deterministic)
}
func (dst *UpdateModuleMetaInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateModuleMetaInfoReq.Merge(dst, src)
}
func (m *UpdateModuleMetaInfoReq) XXX_Size() int {
	return xxx_messageInfo_UpdateModuleMetaInfoReq.Size(m)
}
func (m *UpdateModuleMetaInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateModuleMetaInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateModuleMetaInfoReq proto.InternalMessageInfo

func (m *UpdateModuleMetaInfoReq) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *UpdateModuleMetaInfoReq) GetMetaInfo() *ModuleMetaInfo {
	if m != nil {
		return m.MetaInfo
	}
	return nil
}

type UpdateModuleMetaInfoResp struct {
	Ret                  int32    `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	TraceId              string   `protobuf:"bytes,3,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateModuleMetaInfoResp) Reset()         { *m = UpdateModuleMetaInfoResp{} }
func (m *UpdateModuleMetaInfoResp) String() string { return proto.CompactTextString(m) }
func (*UpdateModuleMetaInfoResp) ProtoMessage()    {}
func (*UpdateModuleMetaInfoResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_d123e24d66c704a9, []int{7}
}
func (m *UpdateModuleMetaInfoResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateModuleMetaInfoResp.Unmarshal(m, b)
}
func (m *UpdateModuleMetaInfoResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateModuleMetaInfoResp.Marshal(b, m, deterministic)
}
func (dst *UpdateModuleMetaInfoResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateModuleMetaInfoResp.Merge(dst, src)
}
func (m *UpdateModuleMetaInfoResp) XXX_Size() int {
	return xxx_messageInfo_UpdateModuleMetaInfoResp.Size(m)
}
func (m *UpdateModuleMetaInfoResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateModuleMetaInfoResp.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateModuleMetaInfoResp proto.InternalMessageInfo

func (m *UpdateModuleMetaInfoResp) GetRet() int32 {
	if m != nil {
		return m.Ret
	}
	return 0
}

func (m *UpdateModuleMetaInfoResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *UpdateModuleMetaInfoResp) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

func init() {
	proto.RegisterType((*VanityImportMetaInfo)(nil), "apidef.VanityImportMetaInfo")
	proto.RegisterType((*SourceMetaInfo)(nil), "apidef.SourceMetaInfo")
	proto.RegisterType((*ModuleMetaInfo)(nil), "apidef.ModuleMetaInfo")
	proto.RegisterType((*SubImportDirToRoot)(nil), "apidef.SubImportDirToRoot")
	proto.RegisterType((*ImportMetaInfoReq)(nil), "apidef.ImportMetaInfoReq")
	proto.RegisterType((*ImportMetaInfoResp)(nil), "apidef.ImportMetaInfoResp")
	proto.RegisterType((*UpdateModuleMetaInfoReq)(nil), "apidef.UpdateModuleMetaInfoReq")
	proto.RegisterType((*UpdateModuleMetaInfoResp)(nil), "apidef.UpdateModuleMetaInfoResp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VanityImportServiceClient is the client API for VanityImportService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VanityImportServiceClient interface {
	QueryImportMetaInfo(ctx context.Context, in *ImportMetaInfoReq, opts ...grpc.CallOption) (*ImportMetaInfoResp, error)
	UpdateModuleMetaInfo(ctx context.Context, in *UpdateModuleMetaInfoReq, opts ...grpc.CallOption) (*UpdateModuleMetaInfoResp, error)
}

type vanityImportServiceClient struct {
	cc *grpc.ClientConn
}

func NewVanityImportServiceClient(cc *grpc.ClientConn) VanityImportServiceClient {
	return &vanityImportServiceClient{cc}
}

func (c *vanityImportServiceClient) QueryImportMetaInfo(ctx context.Context, in *ImportMetaInfoReq, opts ...grpc.CallOption) (*ImportMetaInfoResp, error) {
	out := new(ImportMetaInfoResp)
	err := c.cc.Invoke(ctx, "/apidef.VanityImportService/QueryImportMetaInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vanityImportServiceClient) UpdateModuleMetaInfo(ctx context.Context, in *UpdateModuleMetaInfoReq, opts ...grpc.CallOption) (*UpdateModuleMetaInfoResp, error) {
	out := new(UpdateModuleMetaInfoResp)
	err := c.cc.Invoke(ctx, "/apidef.VanityImportService/UpdateModuleMetaInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VanityImportServiceServer is the server API for VanityImportService service.
type VanityImportServiceServer interface {
	QueryImportMetaInfo(context.Context, *ImportMetaInfoReq) (*ImportMetaInfoResp, error)
	UpdateModuleMetaInfo(context.Context, *UpdateModuleMetaInfoReq) (*UpdateModuleMetaInfoResp, error)
}

func RegisterVanityImportServiceServer(s *grpc.Server, srv VanityImportServiceServer) {
	s.RegisterService(&_VanityImportService_serviceDesc, srv)
}

func _VanityImportService_QueryImportMetaInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportMetaInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VanityImportServiceServer).QueryImportMetaInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apidef.VanityImportService/QueryImportMetaInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VanityImportServiceServer).QueryImportMetaInfo(ctx, req.(*ImportMetaInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _VanityImportService_UpdateModuleMetaInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateModuleMetaInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VanityImportServiceServer).UpdateModuleMetaInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apidef.VanityImportService/UpdateModuleMetaInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VanityImportServiceServer).UpdateModuleMetaInfo(ctx, req.(*UpdateModuleMetaInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _VanityImportService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "apidef.VanityImportService",
	HandlerType: (*VanityImportServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryImportMetaInfo",
			Handler:    _VanityImportService_QueryImportMetaInfo_Handler,
		},
		{
			MethodName: "UpdateModuleMetaInfo",
			Handler:    _VanityImportService_UpdateModuleMetaInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_api_d123e24d66c704a9) }

var fileDescriptor_api_d123e24d66c704a9 = []byte{
	// 527 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0xc5, 0x4d, 0x9b, 0x26, 0x93, 0x36, 0x94, 0x6d, 0x55, 0x9c, 0x00, 0x6a, 0xb0, 0x10, 0xea,
	0x01, 0xa5, 0x52, 0x8b, 0xc4, 0x89, 0x0b, 0xe2, 0x40, 0x0e, 0x45, 0xc5, 0x21, 0x48, 0xc0, 0x21,
	0xda, 0x78, 0x37, 0xc9, 0x4a, 0xb6, 0xc7, 0xd9, 0x5d, 0x47, 0xe2, 0x0f, 0xf8, 0x1c, 0x8e, 0x9c,
	0xf9, 0x32, 0xb4, 0xbb, 0x76, 0x14, 0xa7, 0x29, 0x42, 0x70, 0xdb, 0x99, 0x7d, 0x6f, 0xdf, 0xcc,
	0x9b, 0xb1, 0xa1, 0x49, 0x33, 0xd1, 0xcf, 0x24, 0x6a, 0x24, 0x75, 0x9a, 0x09, 0xc6, 0xa7, 0xc1,
	0x02, 0x4e, 0x3e, 0xd1, 0x54, 0xe8, 0x6f, 0x83, 0x24, 0x43, 0xa9, 0xaf, 0xb9, 0xa6, 0x83, 0x74,
	0x8a, 0xe4, 0x05, 0x90, 0x04, 0x59, 0x1e, 0xf3, 0xb1, 0xb0, 0x17, 0xe3, 0x8c, 0xea, 0xb9, 0xef,
	0xf5, 0xbc, 0xf3, 0x66, 0x78, 0xe4, 0x6e, 0x1c, 0xe3, 0x86, 0xea, 0x39, 0x39, 0x82, 0xda, 0x32,
	0x52, 0xfe, 0x8e, 0xbd, 0x36, 0x47, 0xd2, 0x81, 0x86, 0xe4, 0x19, 0x8e, 0x73, 0x19, 0xfb, 0x35,
	0x9b, 0xde, 0x37, 0xf1, 0x48, 0xc6, 0xc1, 0x4f, 0x0f, 0xda, 0x43, 0xcc, 0x65, 0xc4, 0xff, 0x51,
	0xad, 0x03, 0x8d, 0x39, 0x26, 0xdc, 0xbe, 0xed, 0x24, 0xf7, 0x4d, 0x3c, 0x92, 0x31, 0x39, 0x83,
	0x16, 0x13, 0xd2, 0xd0, 0x35, 0x97, 0x69, 0xa1, 0x0c, 0x4c, 0xc8, 0x1b, 0x97, 0x21, 0x4f, 0xe1,
	0x60, 0x2a, 0x62, 0xbe, 0x42, 0xec, 0x5a, 0x44, 0xcb, 0xe4, 0x4a, 0x48, 0x07, 0x1a, 0x0c, 0xa3,
	0xf1, 0x1c, 0x95, 0xf6, 0xf7, 0xdc, 0xf3, 0x0c, 0xa3, 0x77, 0xa8, 0x74, 0xf0, 0xc3, 0x83, 0xf6,
	0xb5, 0x2d, 0x67, 0x55, 0xfa, 0x6b, 0x68, 0x15, 0x35, 0x8b, 0x74, 0x8a, 0xb6, 0xe6, 0xd6, 0xe5,
	0xe3, 0xbe, 0xb3, 0xb7, 0xbf, 0xcd, 0xdb, 0x10, 0x1c, 0xc1, 0xd2, 0x5f, 0x41, 0x4b, 0x59, 0x2f,
	0x1c, 0x7d, 0xc7, 0xd2, 0x4f, 0x4b, 0x7a, 0xd5, 0xa6, 0x10, 0x1c, 0xd4, 0x12, 0x9f, 0xc3, 0x7d,
	0x95, 0x4f, 0x4a, 0xbf, 0x98, 0x90, 0xca, 0xaf, 0xf5, 0x6a, 0xe7, 0xcd, 0xf0, 0x50, 0xe5, 0x13,
	0x27, 0xf8, 0x56, 0x48, 0x15, 0x4c, 0x80, 0x0c, 0xd7, 0x12, 0x1f, 0x31, 0x44, 0xd4, 0xe4, 0x19,
	0xb4, 0xab, 0xec, 0xc2, 0xec, 0x83, 0x75, 0xb2, 0xd1, 0x90, 0x88, 0x7a, 0x1d, 0xe6, 0xfc, 0x3e,
	0x34, 0xe9, 0x15, 0x2e, 0x78, 0x09, 0x0f, 0x36, 0x5a, 0xe4, 0x0b, 0x33, 0x8a, 0xdb, 0xc3, 0x2c,
	0x5a, 0x37, 0x63, 0x0c, 0xbe, 0x7b, 0x40, 0x36, 0x69, 0x2a, 0x33, 0xbb, 0x24, 0xb9, 0xb6, 0xf8,
	0xbd, 0xd0, 0x1c, 0x4d, 0x26, 0x51, 0xb3, 0x72, 0xbb, 0x12, 0x35, 0x33, 0x23, 0xd2, 0x92, 0x1a,
	0xd3, 0x58, 0xb9, 0x5d, 0x36, 0x1e, 0x30, 0x72, 0x05, 0xcd, 0x84, 0x6b, 0xea, 0xec, 0xdc, 0xad,
	0xda, 0x59, 0x1d, 0x5d, 0xd8, 0x48, 0x8a, 0x53, 0x30, 0x85, 0x87, 0xa3, 0x8c, 0x51, 0xcd, 0x37,
	0x10, 0x7c, 0x41, 0x4e, 0xa1, 0x4e, 0x23, 0x2d, 0x30, 0x2d, 0x3a, 0x28, 0xa2, 0xaa, 0xce, 0xce,
	0x5f, 0xea, 0x7c, 0x06, 0x7f, 0xbb, 0xce, 0x7f, 0xf7, 0x7d, 0xf9, 0xcb, 0x83, 0xe3, 0xf5, 0x6d,
	0x1b, 0x72, 0xb9, 0x14, 0x11, 0x27, 0xef, 0xe1, 0xf8, 0x43, 0xce, 0xe5, 0xe6, 0xf7, 0xdd, 0x29,
	0x6b, 0xbd, 0x35, 0xb8, 0x6e, 0xf7, 0xae, 0x2b, 0x95, 0x05, 0xf7, 0xc8, 0x57, 0x38, 0xd9, 0xd6,
	0x02, 0x39, 0x2b, 0x59, 0x77, 0x18, 0xd9, 0xed, 0xfd, 0x19, 0x60, 0x1e, 0x7f, 0xf3, 0xe4, 0xcb,
	0xa3, 0x19, 0x2e, 0x6d, 0x17, 0x6e, 0x51, 0x2e, 0xec, 0xdf, 0xea, 0xc2, 0x31, 0x27, 0x75, 0x1b,
	0x5d, 0xfd, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xbf, 0x3f, 0x66, 0xa2, 0xc8, 0x04, 0x00, 0x00,
}
